################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
AI_App \
Application/User/AZURE_RTOS/App \
Application/User/Core \
Application/User/FileX/App \
Application/User/FileX/Target \
Application/User/Startup \
BSP/BQ27441 \
BSP/EEPROM \
BSP/HyperRAM \
BSP/KEY \
BSP/LED \
BSP/RGBLCD \
BSP/SD_NAND \
BSP/SYS \
BSP/TOUCH \
BSP/Tiny1C/VDCMD \
BSP/Tiny1C \
Drivers/CMSIS \
Drivers/STM32N6xx_HAL_Driver \
FileX_Common_Src \
FileX_SD_Driver_Src \
Middlewares/AI/Npu/Devices/STM32N6XX \
Middlewares/AI/Npu/ll_aton \
ThreadX_Common_Src \
ThreadX_Port_Src \
gui_guider/custom \
gui_guider/generated \
gui_guider/generated/guider_fonts \
gui_guider/generated/images \
lvgl/porting \
lvgl/src/core \
lvgl/src/draw/arm2d \
lvgl/src/draw \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/nxp/vglite \
lvgl/src/draw/renesas \
lvgl/src/draw/sdl \
lvgl/src/draw/stm32_dma2d \
lvgl/src/draw/sw \
lvgl/src/draw/swm341_dma2d \
lvgl/src/extra/layouts/flex \
lvgl/src/extra/layouts/grid \
lvgl/src/extra/libs/bmp \
lvgl/src/extra/libs/ffmpeg \
lvgl/src/extra/libs/freetype \
lvgl/src/extra/libs/fsdrv \
lvgl/src/extra/libs/gif \
lvgl/src/extra/libs/png \
lvgl/src/extra/libs/qrcode \
lvgl/src/extra/libs/rlottie \
lvgl/src/extra/libs/sjpg \
lvgl/src/extra/libs/tiny_ttf \
lvgl/src/extra \
lvgl/src/extra/others/fragment \
lvgl/src/extra/others/gridnav \
lvgl/src/extra/others/ime \
lvgl/src/extra/others/imgfont \
lvgl/src/extra/others/monkey \
lvgl/src/extra/others/msg \
lvgl/src/extra/others/snapshot \
lvgl/src/extra/themes/basic \
lvgl/src/extra/themes/default \
lvgl/src/extra/themes/mono \
lvgl/src/extra/widgets/animimg \
lvgl/src/extra/widgets/calendar \
lvgl/src/extra/widgets/chart \
lvgl/src/extra/widgets/colorwheel \
lvgl/src/extra/widgets/imgbtn \
lvgl/src/extra/widgets/keyboard \
lvgl/src/extra/widgets/led \
lvgl/src/extra/widgets/list \
lvgl/src/extra/widgets/menu \
lvgl/src/extra/widgets/meter \
lvgl/src/extra/widgets/msgbox \
lvgl/src/extra/widgets/span \
lvgl/src/extra/widgets/spinbox \
lvgl/src/extra/widgets/spinner \
lvgl/src/extra/widgets/tabview \
lvgl/src/extra/widgets/tileview \
lvgl/src/extra/widgets/win \
lvgl/src/font \
lvgl/src/hal \
lvgl/src/misc \
lvgl/src/widgets \

