################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack.c \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/txe_thread_secure_stack_allocate.c \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/txe_thread_secure_stack_free.c 

S_UPPER_SRCS += \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_context_restore.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_context_save.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_interrupt_control.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_interrupt_disable.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_interrupt_restore.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_schedule.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack_allocate.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack_free.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack_initialize.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_stack_build.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_system_return.S \
D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_timer_interrupt.S 

OBJS += \
./ThreadX_Port_Src/tx_thread_context_restore.o \
./ThreadX_Port_Src/tx_thread_context_save.o \
./ThreadX_Port_Src/tx_thread_interrupt_control.o \
./ThreadX_Port_Src/tx_thread_interrupt_disable.o \
./ThreadX_Port_Src/tx_thread_interrupt_restore.o \
./ThreadX_Port_Src/tx_thread_schedule.o \
./ThreadX_Port_Src/tx_thread_secure_stack.o \
./ThreadX_Port_Src/tx_thread_secure_stack_allocate.o \
./ThreadX_Port_Src/tx_thread_secure_stack_free.o \
./ThreadX_Port_Src/tx_thread_secure_stack_initialize.o \
./ThreadX_Port_Src/tx_thread_stack_build.o \
./ThreadX_Port_Src/tx_thread_system_return.o \
./ThreadX_Port_Src/tx_timer_interrupt.o \
./ThreadX_Port_Src/txe_thread_secure_stack_allocate.o \
./ThreadX_Port_Src/txe_thread_secure_stack_free.o 

S_UPPER_DEPS += \
./ThreadX_Port_Src/tx_thread_context_restore.d \
./ThreadX_Port_Src/tx_thread_context_save.d \
./ThreadX_Port_Src/tx_thread_interrupt_control.d \
./ThreadX_Port_Src/tx_thread_interrupt_disable.d \
./ThreadX_Port_Src/tx_thread_interrupt_restore.d \
./ThreadX_Port_Src/tx_thread_schedule.d \
./ThreadX_Port_Src/tx_thread_secure_stack_allocate.d \
./ThreadX_Port_Src/tx_thread_secure_stack_free.d \
./ThreadX_Port_Src/tx_thread_secure_stack_initialize.d \
./ThreadX_Port_Src/tx_thread_stack_build.d \
./ThreadX_Port_Src/tx_thread_system_return.d \
./ThreadX_Port_Src/tx_timer_interrupt.d 

C_DEPS += \
./ThreadX_Port_Src/tx_thread_secure_stack.d \
./ThreadX_Port_Src/txe_thread_secure_stack_allocate.d \
./ThreadX_Port_Src/txe_thread_secure_stack_free.d 


# Each subdirectory must supply rules for building sources it contributes
ThreadX_Port_Src/tx_thread_context_restore.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_context_restore.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_context_save.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_context_save.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_interrupt_control.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_interrupt_control.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_interrupt_disable.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_interrupt_disable.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_interrupt_restore.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_interrupt_restore.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_schedule.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_schedule.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_secure_stack.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack.c ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -DFX_INCLUDE_USER_DEFINE_FILE -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_EB_DBG_INFO -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/BSP" -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/lvgl" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/lvgl/porting" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/gui_guider/custom" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/gui_guider/generated" -I../../../Appli/AZURE_RTOS/App -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -I../../../Middlewares/ST/AI/Npu/Devices/STM32N6XX -I../../../ExtMemLoader/X-CUBE-AI/App -I../../../Middlewares/ST/AI/Inc -I../../../Middlewares/ST/AI/Npu/ll_aton -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
ThreadX_Port_Src/tx_thread_secure_stack_allocate.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack_allocate.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_secure_stack_free.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack_free.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_secure_stack_initialize.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_secure_stack_initialize.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_stack_build.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_stack_build.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_thread_system_return.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_thread_system_return.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/tx_timer_interrupt.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/tx_timer_interrupt.S ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m55 -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Drivers/CMSIS/Include -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
ThreadX_Port_Src/txe_thread_secure_stack_allocate.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/txe_thread_secure_stack_allocate.c ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -DFX_INCLUDE_USER_DEFINE_FILE -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_EB_DBG_INFO -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/BSP" -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/lvgl" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/lvgl/porting" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/gui_guider/custom" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/gui_guider/generated" -I../../../Appli/AZURE_RTOS/App -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -I../../../Middlewares/ST/AI/Npu/Devices/STM32N6XX -I../../../ExtMemLoader/X-CUBE-AI/App -I../../../Middlewares/ST/AI/Inc -I../../../Middlewares/ST/AI/Npu/ll_aton -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
ThreadX_Port_Src/txe_thread_secure_stack_free.o: D:/PracticeProject/Stm32/stm32n6_thermal/Middlewares/ST/threadx/ports/cortex_m55/gnu/src/txe_thread_secure_stack_free.c ThreadX_Port_Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DTX_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -DFX_INCLUDE_USER_DEFINE_FILE -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_EB_DBG_INFO -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/BSP" -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/lvgl" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/lvgl/porting" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/gui_guider/custom" -I"D:/PracticeProject/Stm32/stm32n6_thermal/STM32CubeIDE/Appli/gui_guider/generated" -I../../../Appli/AZURE_RTOS/App -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Appli/FileX/App -I../../../Appli/FileX/Target -I../../../Middlewares/ST/filex/common/inc -I../../../Middlewares/ST/filex/ports/generic/inc -I../../../Middlewares/ST/AI/Npu/Devices/STM32N6XX -I../../../ExtMemLoader/X-CUBE-AI/App -I../../../Middlewares/ST/AI/Inc -I../../../Middlewares/ST/AI/Npu/ll_aton -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-ThreadX_Port_Src

clean-ThreadX_Port_Src:
	-$(RM) ./ThreadX_Port_Src/tx_thread_context_restore.d ./ThreadX_Port_Src/tx_thread_context_restore.o ./ThreadX_Port_Src/tx_thread_context_save.d ./ThreadX_Port_Src/tx_thread_context_save.o ./ThreadX_Port_Src/tx_thread_interrupt_control.d ./ThreadX_Port_Src/tx_thread_interrupt_control.o ./ThreadX_Port_Src/tx_thread_interrupt_disable.d ./ThreadX_Port_Src/tx_thread_interrupt_disable.o ./ThreadX_Port_Src/tx_thread_interrupt_restore.d ./ThreadX_Port_Src/tx_thread_interrupt_restore.o ./ThreadX_Port_Src/tx_thread_schedule.d ./ThreadX_Port_Src/tx_thread_schedule.o ./ThreadX_Port_Src/tx_thread_secure_stack.cyclo ./ThreadX_Port_Src/tx_thread_secure_stack.d ./ThreadX_Port_Src/tx_thread_secure_stack.o ./ThreadX_Port_Src/tx_thread_secure_stack.su ./ThreadX_Port_Src/tx_thread_secure_stack_allocate.d ./ThreadX_Port_Src/tx_thread_secure_stack_allocate.o ./ThreadX_Port_Src/tx_thread_secure_stack_free.d ./ThreadX_Port_Src/tx_thread_secure_stack_free.o ./ThreadX_Port_Src/tx_thread_secure_stack_initialize.d ./ThreadX_Port_Src/tx_thread_secure_stack_initialize.o ./ThreadX_Port_Src/tx_thread_stack_build.d ./ThreadX_Port_Src/tx_thread_stack_build.o ./ThreadX_Port_Src/tx_thread_system_return.d ./ThreadX_Port_Src/tx_thread_system_return.o ./ThreadX_Port_Src/tx_timer_interrupt.d ./ThreadX_Port_Src/tx_timer_interrupt.o ./ThreadX_Port_Src/txe_thread_secure_stack_allocate.cyclo ./ThreadX_Port_Src/txe_thread_secure_stack_allocate.d ./ThreadX_Port_Src/txe_thread_secure_stack_allocate.o ./ThreadX_Port_Src/txe_thread_secure_stack_allocate.su ./ThreadX_Port_Src/txe_thread_secure_stack_free.cyclo ./ThreadX_Port_Src/txe_thread_secure_stack_free.d ./ThreadX_Port_Src/txe_thread_secure_stack_free.o ./ThreadX_Port_Src/txe_thread_secure_stack_free.su

.PHONY: clean-ThreadX_Port_Src

